server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://47.104.138.21:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 100
      max-wait: 1000
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 28800

mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.cv.mycar.dao.model
  mapper-locations: classpath:mapper/*Mapper.xml
  check-config-location: true
mapper:
  not-empty: true
  identity: MYSQL
#  mappers:
#mapper.mappers= - com.vector.dubbo.dao.util.MyBaseMapper

