server:
  port: 8071
logging:
 root:
   level: DEBUG
spring:
  redis:
    host: 47.104.138.21
    port: 6378
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

